# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: YelovSK.Dameview
PackageVersion: 1.9.0
InstallerType: exe
Scope: user
InstallModes:
- interactive
- silent
- silentWithProgress
InstallerSwitches:
  Silent: --install --silent
  SilentWithProgress: --install --silent
  Interactive: --install
UpgradeBehavior: install
ProductCode: Dameview
AppsAndFeaturesEntries:
- DisplayName: Dameview
  Publisher: YelovSK
  ProductCode: Dameview
InstallationMetadata:
  DefaultInstallLocation: '%LOCALAPPDATA%\Programs\Dameview'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/YelovSK/Dameview/releases/download/v1.9.0/Dameview.exe
  InstallerSha256: 906000B29442BF694C2CAB260780E8C5E7E99BE33736494C2521808D96301464
ManifestType: installer
ManifestVersion: 1.12.0
ReleaseDate: 2026-09-27
